---
title: getBounds
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
name: getBounds
header-img: header-2.png
email: malcolmtmeyer@gmail.com
description: A (Jekyll) Blog Exploring Web Maps & Cartography
baseurl: https://getbounds.com
testurl: https://reyemtm.github.io
url: https://getbounds.com
twitter_username: getbounds
github_username: reyemtm
google+_usename: malcolmmeyer
facebook_username: 
linkedin_username: malcolm-meyer/44/2a2/577
author: Malcolm Meyer
mapboxid: pk.eyJ1IjoicmV5ZW10bSIsImEiOiJCTHUxSVZ3In0.Q-qbg_jG0JcT6bfBeiwXQg
markdown: kramdown
highlighter: rouge
paginate: 10
exclude:
- less
- node_modules
- Gruntfile.js
- package.json
- README.md
include:
- _pages
gems:
- jekyll-sitemap
- jekyll-paginate
